// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalFinanceApp.Infrastructure.Data;

#nullable disable

namespace PersonalFinanceApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260906053649_SeedAdminRole")]
    partial class SeedAdminRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000002",
                            ConcurrencyStamp = "7480c257-7483-4912-9be3-7c5418edc6b6",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000001",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cca984db-acc2-4025-9fbf-42403506eab4"),
                            ColorHex = "#3B82F6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Children"
                        },
                        new
                        {
                            Id = new Guid("dbc9d96f-9858-4b75-8784-6e68da415e28"),
                            ColorHex = "#3B82F6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Activities",
                            ParentCategoryId = new Guid("cca984db-acc2-4025-9fbf-42403506eab4")
                        },
                        new
                        {
                            Id = new Guid("581b99b6-9564-49f4-811c-572231945d87"),
                            ColorHex = "#3B82F6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Allowance",
                            ParentCategoryId = new Guid("cca984db-acc2-4025-9fbf-42403506eab4")
                        },
                        new
                        {
                            Id = new Guid("ab7286e5-ec96-40f8-884c-d30d149c84b1"),
                            ColorHex = "#3B82F6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Medical Expenses",
                            ParentCategoryId = new Guid("cca984db-acc2-4025-9fbf-42403506eab4")
                        },
                        new
                        {
                            Id = new Guid("76082b7d-9be5-4996-ba9b-d6bdb19ca85c"),
                            ColorHex = "#3B82F6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Childcare",
                            ParentCategoryId = new Guid("cca984db-acc2-4025-9fbf-42403506eab4")
                        },
                        new
                        {
                            Id = new Guid("e500b73d-8f24-45e3-bbb5-3010f96efac5"),
                            ColorHex = "#3B82F6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Clothing",
                            ParentCategoryId = new Guid("cca984db-acc2-4025-9fbf-42403506eab4")
                        },
                        new
                        {
                            Id = new Guid("6e51f026-eb45-4d49-898c-da57c4d197f2"),
                            ColorHex = "#3B82F6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Education",
                            ParentCategoryId = new Guid("cca984db-acc2-4025-9fbf-42403506eab4")
                        },
                        new
                        {
                            Id = new Guid("785464c5-3da7-4c0e-9d92-878ab3075a85"),
                            ColorHex = "#3B82F6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Toys",
                            ParentCategoryId = new Guid("cca984db-acc2-4025-9fbf-42403506eab4")
                        },
                        new
                        {
                            Id = new Guid("c518203d-2922-479e-a14b-d50f029dcbbf"),
                            ColorHex = "#3B82F6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("cca984db-acc2-4025-9fbf-42403506eab4")
                        },
                        new
                        {
                            Id = new Guid("43c72a81-8ff7-4bac-a0fa-2d2ad50bfa6a"),
                            ColorHex = "#EF4444",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Debt"
                        },
                        new
                        {
                            Id = new Guid("2b199eb2-6f9d-4b8c-b18a-0176b03bfb20"),
                            ColorHex = "#EF4444",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Credit Cards",
                            ParentCategoryId = new Guid("43c72a81-8ff7-4bac-a0fa-2d2ad50bfa6a")
                        },
                        new
                        {
                            Id = new Guid("e0194d83-e9e6-4b13-9ba7-39fa8a98d36e"),
                            ColorHex = "#EF4444",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Student Loans",
                            ParentCategoryId = new Guid("43c72a81-8ff7-4bac-a0fa-2d2ad50bfa6a")
                        },
                        new
                        {
                            Id = new Guid("3a603453-0ca4-4fe5-8bd7-62dee510b486"),
                            ColorHex = "#EF4444",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other Loans",
                            ParentCategoryId = new Guid("43c72a81-8ff7-4bac-a0fa-2d2ad50bfa6a")
                        },
                        new
                        {
                            Id = new Guid("7ea12b1b-73eb-4374-9d7c-b2709cc4b051"),
                            ColorHex = "#EF4444",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mortgage",
                            ParentCategoryId = new Guid("43c72a81-8ff7-4bac-a0fa-2d2ad50bfa6a")
                        },
                        new
                        {
                            Id = new Guid("21a0011a-7e1f-4be1-a060-3dd9a124716e"),
                            ColorHex = "#EF4444",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("43c72a81-8ff7-4bac-a0fa-2d2ad50bfa6a")
                        },
                        new
                        {
                            Id = new Guid("bb056a43-2fb9-4b1b-8d49-04cf324a1ede"),
                            ColorHex = "#8B5CF6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("ff1bfbd7-4c49-4ecc-aec2-52d6df9788d1"),
                            ColorHex = "#8B5CF6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tuition",
                            ParentCategoryId = new Guid("bb056a43-2fb9-4b1b-8d49-04cf324a1ede")
                        },
                        new
                        {
                            Id = new Guid("aed1a3f2-1211-4100-ba25-da55af9ddef8"),
                            ColorHex = "#8B5CF6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Books",
                            ParentCategoryId = new Guid("bb056a43-2fb9-4b1b-8d49-04cf324a1ede")
                        },
                        new
                        {
                            Id = new Guid("ec37be8c-c5f2-44bc-aedf-ebba84ee428e"),
                            ColorHex = "#8B5CF6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Certifications",
                            ParentCategoryId = new Guid("bb056a43-2fb9-4b1b-8d49-04cf324a1ede")
                        },
                        new
                        {
                            Id = new Guid("984790f0-f7a6-4862-93c8-b7d44799a4be"),
                            ColorHex = "#8B5CF6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Courses",
                            ParentCategoryId = new Guid("bb056a43-2fb9-4b1b-8d49-04cf324a1ede")
                        },
                        new
                        {
                            Id = new Guid("587ab4de-997d-4abc-b7d9-c038a58032df"),
                            ColorHex = "#8B5CF6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Monthly Fee",
                            ParentCategoryId = new Guid("bb056a43-2fb9-4b1b-8d49-04cf324a1ede")
                        },
                        new
                        {
                            Id = new Guid("28edff1b-00a3-4f92-a85f-b40c12416ef4"),
                            ColorHex = "#8B5CF6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("bb056a43-2fb9-4b1b-8d49-04cf324a1ede")
                        },
                        new
                        {
                            Id = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = new Guid("15bf2360-0d29-4036-8e36-ea8c7b61c31b"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Books",
                            ParentCategoryId = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf")
                        },
                        new
                        {
                            Id = new Guid("d44a7913-b964-4068-bd78-0e581f906d59"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Concerts & Shows",
                            ParentCategoryId = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf")
                        },
                        new
                        {
                            Id = new Guid("b6daaa27-cf8d-4166-a109-2b616cf9841b"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Games",
                            ParentCategoryId = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf")
                        },
                        new
                        {
                            Id = new Guid("1f6a08c2-8a10-48e1-9171-5859dc63c194"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hobbies",
                            ParentCategoryId = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf")
                        },
                        new
                        {
                            Id = new Guid("bb945eac-a7cb-4a07-84a8-7f782680f922"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Movies",
                            ParentCategoryId = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf")
                        },
                        new
                        {
                            Id = new Guid("fcba3eff-bba2-4f8d-987c-1851d6d73865"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Music",
                            ParentCategoryId = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf")
                        },
                        new
                        {
                            Id = new Guid("38e811b5-67de-4b01-b360-cc6042a41eef"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Outdoor Activities",
                            ParentCategoryId = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf")
                        },
                        new
                        {
                            Id = new Guid("34faf741-74c3-42cc-aef7-3ed6bfa22488"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Photography",
                            ParentCategoryId = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf")
                        },
                        new
                        {
                            Id = new Guid("ebcdfa02-0206-45a1-b39d-d12814d1fc75"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sports",
                            ParentCategoryId = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf")
                        },
                        new
                        {
                            Id = new Guid("1d2a6df6-81a4-4947-bd49-7dbdfbff8af6"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cinema & Theater",
                            ParentCategoryId = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf")
                        },
                        new
                        {
                            Id = new Guid("c420e2e2-89f2-4489-8a24-03443db1a0cf"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Television",
                            ParentCategoryId = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf")
                        },
                        new
                        {
                            Id = new Guid("e628eade-9382-4917-af77-fd2824d85d1e"),
                            ColorHex = "#EC4899",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("6271d373-31e6-4b8d-b431-9ae25de97daf")
                        },
                        new
                        {
                            Id = new Guid("2b22a05b-fef1-4d3f-9178-99ebe12519b3"),
                            ColorHex = "#10B981",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Everyday"
                        },
                        new
                        {
                            Id = new Guid("3dfe2adc-3067-4cbf-b8b0-4a62e492c563"),
                            ColorHex = "#10B981",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Groceries",
                            ParentCategoryId = new Guid("2b22a05b-fef1-4d3f-9178-99ebe12519b3")
                        },
                        new
                        {
                            Id = new Guid("dbf68cf2-df95-45dd-9332-0ce6c4efb750"),
                            ColorHex = "#10B981",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dining Out",
                            ParentCategoryId = new Guid("2b22a05b-fef1-4d3f-9178-99ebe12519b3")
                        },
                        new
                        {
                            Id = new Guid("aa9eb638-848f-44f3-8b1d-0d983e8bd9b6"),
                            ColorHex = "#10B981",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Personal Care",
                            ParentCategoryId = new Guid("2b22a05b-fef1-4d3f-9178-99ebe12519b3")
                        },
                        new
                        {
                            Id = new Guid("0b40bf61-cd4c-4d4f-9930-8cff43d9bfe9"),
                            ColorHex = "#10B981",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Clothing",
                            ParentCategoryId = new Guid("2b22a05b-fef1-4d3f-9178-99ebe12519b3")
                        },
                        new
                        {
                            Id = new Guid("08853dbe-992c-4f67-b731-cd0f097c1a25"),
                            ColorHex = "#10B981",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Laundry & Dry Cleaning",
                            ParentCategoryId = new Guid("2b22a05b-fef1-4d3f-9178-99ebe12519b3")
                        },
                        new
                        {
                            Id = new Guid("44988d2e-a13d-4a23-b8c8-034824bd8f04"),
                            ColorHex = "#10B981",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hair & Beauty",
                            ParentCategoryId = new Guid("2b22a05b-fef1-4d3f-9178-99ebe12519b3")
                        },
                        new
                        {
                            Id = new Guid("ffcc2f24-f25f-47e8-9557-31c6257fd5b9"),
                            ColorHex = "#10B981",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Subscriptions",
                            ParentCategoryId = new Guid("2b22a05b-fef1-4d3f-9178-99ebe12519b3")
                        },
                        new
                        {
                            Id = new Guid("d2c2f5de-facd-41d8-815a-a311c061d642"),
                            ColorHex = "#10B981",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("2b22a05b-fef1-4d3f-9178-99ebe12519b3")
                        },
                        new
                        {
                            Id = new Guid("244fb274-3a5e-40e2-b80b-5e0fee60bd1b"),
                            ColorHex = "#F472B6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gifts & Donations"
                        },
                        new
                        {
                            Id = new Guid("ca73e76e-efad-40f0-a86e-f17801d9e2ac"),
                            ColorHex = "#F472B6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gifts",
                            ParentCategoryId = new Guid("244fb274-3a5e-40e2-b80b-5e0fee60bd1b")
                        },
                        new
                        {
                            Id = new Guid("a12fa006-213e-491b-8c13-c0094fdfa280"),
                            ColorHex = "#F472B6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Charity",
                            ParentCategoryId = new Guid("244fb274-3a5e-40e2-b80b-5e0fee60bd1b")
                        },
                        new
                        {
                            Id = new Guid("9b27237a-ce27-400b-a2b2-9436fd3a9df5"),
                            ColorHex = "#F472B6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("244fb274-3a5e-40e2-b80b-5e0fee60bd1b")
                        },
                        new
                        {
                            Id = new Guid("80ce73e4-5200-4ecd-9011-ea1c5f43be6e"),
                            ColorHex = "#14B8A6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("bbcedb10-ee32-4443-8cfd-849c7771f29a"),
                            ColorHex = "#14B8A6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Doctors",
                            ParentCategoryId = new Guid("80ce73e4-5200-4ecd-9011-ea1c5f43be6e")
                        },
                        new
                        {
                            Id = new Guid("679dd9ed-b574-4df2-8911-d258507738e7"),
                            ColorHex = "#14B8A6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Specialists",
                            ParentCategoryId = new Guid("80ce73e4-5200-4ecd-9011-ea1c5f43be6e")
                        },
                        new
                        {
                            Id = new Guid("5b9b7f79-f4b8-4ffb-9015-40cb6485c6f5"),
                            ColorHex = "#14B8A6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pharmacy",
                            ParentCategoryId = new Guid("80ce73e4-5200-4ecd-9011-ea1c5f43be6e")
                        },
                        new
                        {
                            Id = new Guid("1fc92633-805c-4848-9016-2a21cc04a564"),
                            ColorHex = "#14B8A6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Emergency",
                            ParentCategoryId = new Guid("80ce73e4-5200-4ecd-9011-ea1c5f43be6e")
                        },
                        new
                        {
                            Id = new Guid("fc229278-d418-4947-b4a3-7535c9dbeaa2"),
                            ColorHex = "#14B8A6",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("80ce73e4-5200-4ecd-9011-ea1c5f43be6e")
                        },
                        new
                        {
                            Id = new Guid("92405c01-5cc5-458c-9fc2-7110d4b023ee"),
                            ColorHex = "#6366F1",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Housing"
                        },
                        new
                        {
                            Id = new Guid("dbcdc4fa-4395-4786-a335-1c43878c44c4"),
                            ColorHex = "#6366F1",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rent or Mortgage",
                            ParentCategoryId = new Guid("92405c01-5cc5-458c-9fc2-7110d4b023ee")
                        },
                        new
                        {
                            Id = new Guid("c32895ab-21a7-491f-a7f7-ba895bd0eba2"),
                            ColorHex = "#6366F1",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Property Taxes",
                            ParentCategoryId = new Guid("92405c01-5cc5-458c-9fc2-7110d4b023ee")
                        },
                        new
                        {
                            Id = new Guid("6bc2d146-4522-46bf-bb8c-58fe50cab6ee"),
                            ColorHex = "#6366F1",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Furniture",
                            ParentCategoryId = new Guid("92405c01-5cc5-458c-9fc2-7110d4b023ee")
                        },
                        new
                        {
                            Id = new Guid("d62b463c-92ae-43b0-a055-37fd29c9193f"),
                            ColorHex = "#6366F1",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Lawn & Garden",
                            ParentCategoryId = new Guid("92405c01-5cc5-458c-9fc2-7110d4b023ee")
                        },
                        new
                        {
                            Id = new Guid("a65d827e-87e8-4075-bffe-c65ab578e128"),
                            ColorHex = "#6366F1",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Home Goods",
                            ParentCategoryId = new Guid("92405c01-5cc5-458c-9fc2-7110d4b023ee")
                        },
                        new
                        {
                            Id = new Guid("66fce58f-8ee7-424d-bbe3-2eafd35840b9"),
                            ColorHex = "#6366F1",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Maintenance",
                            ParentCategoryId = new Guid("92405c01-5cc5-458c-9fc2-7110d4b023ee")
                        },
                        new
                        {
                            Id = new Guid("bae067af-7ae9-4d0f-9b51-87b67e84b968"),
                            ColorHex = "#6366F1",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Home Improvements",
                            ParentCategoryId = new Guid("92405c01-5cc5-458c-9fc2-7110d4b023ee")
                        },
                        new
                        {
                            Id = new Guid("fa985bb1-50a9-4f48-8540-1c1392cf9a87"),
                            ColorHex = "#6366F1",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Moving",
                            ParentCategoryId = new Guid("92405c01-5cc5-458c-9fc2-7110d4b023ee")
                        },
                        new
                        {
                            Id = new Guid("250341a6-076a-4cd5-bcb0-49e836633009"),
                            ColorHex = "#6366F1",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("92405c01-5cc5-458c-9fc2-7110d4b023ee")
                        },
                        new
                        {
                            Id = new Guid("b6ea5813-ebdc-4723-9cde-50c2165dd094"),
                            ColorHex = "#F59E0B",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = new Guid("669b13a0-cf32-49f9-8543-d316ef4ba807"),
                            ColorHex = "#F59E0B",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Vehicle",
                            ParentCategoryId = new Guid("b6ea5813-ebdc-4723-9cde-50c2165dd094")
                        },
                        new
                        {
                            Id = new Guid("60c376c0-9f71-4a47-95cf-3b30102742d5"),
                            ColorHex = "#F59E0B",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Health",
                            ParentCategoryId = new Guid("b6ea5813-ebdc-4723-9cde-50c2165dd094")
                        },
                        new
                        {
                            Id = new Guid("9dafcf6a-9892-4048-ada6-370706b4dc64"),
                            ColorHex = "#F59E0B",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Home",
                            ParentCategoryId = new Guid("b6ea5813-ebdc-4723-9cde-50c2165dd094")
                        },
                        new
                        {
                            Id = new Guid("22d7e4b7-725d-444d-b44b-d3f2a239fcc0"),
                            ColorHex = "#F59E0B",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Life",
                            ParentCategoryId = new Guid("b6ea5813-ebdc-4723-9cde-50c2165dd094")
                        },
                        new
                        {
                            Id = new Guid("f3df04bc-4662-4293-aedc-5e1ed630a866"),
                            ColorHex = "#F59E0B",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("b6ea5813-ebdc-4723-9cde-50c2165dd094")
                        },
                        new
                        {
                            Id = new Guid("a90e1c7a-c110-4a33-86fe-6cf5452af73d"),
                            ColorHex = "#84CC16",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pets"
                        },
                        new
                        {
                            Id = new Guid("290ad8f2-7e95-4823-89e2-3c03465f5a98"),
                            ColorHex = "#84CC16",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Food",
                            ParentCategoryId = new Guid("a90e1c7a-c110-4a33-86fe-6cf5452af73d")
                        },
                        new
                        {
                            Id = new Guid("3ab636cb-9efc-4f07-9bf5-0f05bc7373bd"),
                            ColorHex = "#84CC16",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Vet & Medications",
                            ParentCategoryId = new Guid("a90e1c7a-c110-4a33-86fe-6cf5452af73d")
                        },
                        new
                        {
                            Id = new Guid("73a5cad0-5c6f-4409-ab64-bcd616fe8284"),
                            ColorHex = "#84CC16",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Toys",
                            ParentCategoryId = new Guid("a90e1c7a-c110-4a33-86fe-6cf5452af73d")
                        },
                        new
                        {
                            Id = new Guid("192ff9f6-d05b-48ec-b75c-e31dee1bdbd3"),
                            ColorHex = "#84CC16",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Supplies",
                            ParentCategoryId = new Guid("a90e1c7a-c110-4a33-86fe-6cf5452af73d")
                        },
                        new
                        {
                            Id = new Guid("b431cd2c-98fe-4eb1-b3d9-35df37dfc19f"),
                            ColorHex = "#84CC16",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("a90e1c7a-c110-4a33-86fe-6cf5452af73d")
                        },
                        new
                        {
                            Id = new Guid("747990dd-6039-441c-8093-de2ee9bb010b"),
                            ColorHex = "#64748B",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("476ee32a-748c-4e3c-ad5a-05554729e57e"),
                            ColorHex = "#64748B",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Domains & Hosting",
                            ParentCategoryId = new Guid("747990dd-6039-441c-8093-de2ee9bb010b")
                        },
                        new
                        {
                            Id = new Guid("08960f83-02ad-4ab3-afe6-2749c787a98a"),
                            ColorHex = "#64748B",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Online Services",
                            ParentCategoryId = new Guid("747990dd-6039-441c-8093-de2ee9bb010b")
                        },
                        new
                        {
                            Id = new Guid("834da54d-e14b-477f-99d0-9afb66468121"),
                            ColorHex = "#64748B",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hardware",
                            ParentCategoryId = new Guid("747990dd-6039-441c-8093-de2ee9bb010b")
                        },
                        new
                        {
                            Id = new Guid("e033e1e1-44e7-41fb-be08-7a287f4eb83a"),
                            ColorHex = "#64748B",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Software",
                            ParentCategoryId = new Guid("747990dd-6039-441c-8093-de2ee9bb010b")
                        },
                        new
                        {
                            Id = new Guid("62935e1c-fbc0-4033-b31c-788567b784f1"),
                            ColorHex = "#64748B",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("747990dd-6039-441c-8093-de2ee9bb010b")
                        },
                        new
                        {
                            Id = new Guid("47129cd9-9a13-4ea7-914d-d09b59bb21f6"),
                            ColorHex = "#F97316",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = new Guid("af0e21a5-1927-4aea-ac41-dfeda4a4d0cc"),
                            ColorHex = "#F97316",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fuel",
                            ParentCategoryId = new Guid("47129cd9-9a13-4ea7-914d-d09b59bb21f6")
                        },
                        new
                        {
                            Id = new Guid("1cf1d3d7-5057-4d3c-82e3-a9120ac15a1e"),
                            ColorHex = "#F97316",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Vehicle Payments",
                            ParentCategoryId = new Guid("47129cd9-9a13-4ea7-914d-d09b59bb21f6")
                        },
                        new
                        {
                            Id = new Guid("388ef714-c2ac-45d6-aea0-b681a5d7e214"),
                            ColorHex = "#F97316",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Repairs",
                            ParentCategoryId = new Guid("47129cd9-9a13-4ea7-914d-d09b59bb21f6")
                        },
                        new
                        {
                            Id = new Guid("1ec85c04-8c2b-4bbb-a316-d9eee99f9ace"),
                            ColorHex = "#F97316",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Registration & Licensing",
                            ParentCategoryId = new Guid("47129cd9-9a13-4ea7-914d-d09b59bb21f6")
                        },
                        new
                        {
                            Id = new Guid("403fc629-37d2-4afe-9518-57e6f15455b6"),
                            ColorHex = "#F97316",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Supplies",
                            ParentCategoryId = new Guid("47129cd9-9a13-4ea7-914d-d09b59bb21f6")
                        },
                        new
                        {
                            Id = new Guid("7dc9e1a2-ce15-4aa5-aee3-8b042f7d802d"),
                            ColorHex = "#F97316",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Public Transit",
                            ParentCategoryId = new Guid("47129cd9-9a13-4ea7-914d-d09b59bb21f6")
                        },
                        new
                        {
                            Id = new Guid("470449ec-2603-44d5-bfda-e8475c369228"),
                            ColorHex = "#F97316",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Car Wash",
                            ParentCategoryId = new Guid("47129cd9-9a13-4ea7-914d-d09b59bb21f6")
                        },
                        new
                        {
                            Id = new Guid("ff1f078f-3a61-4be6-b3dd-0699709412e3"),
                            ColorHex = "#F97316",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("47129cd9-9a13-4ea7-914d-d09b59bb21f6")
                        },
                        new
                        {
                            Id = new Guid("8c6e5427-76ee-4a4b-9c37-f223ec668754"),
                            ColorHex = "#06B6D4",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Travel"
                        },
                        new
                        {
                            Id = new Guid("9cd0d6ac-64b0-40a0-b5e7-6972493377f1"),
                            ColorHex = "#06B6D4",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Airfare",
                            ParentCategoryId = new Guid("8c6e5427-76ee-4a4b-9c37-f223ec668754")
                        },
                        new
                        {
                            Id = new Guid("3a2cb2c2-7783-42e3-b468-8fe84ae60fb7"),
                            ColorHex = "#06B6D4",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hotels",
                            ParentCategoryId = new Guid("8c6e5427-76ee-4a4b-9c37-f223ec668754")
                        },
                        new
                        {
                            Id = new Guid("2bbb8078-cacf-4a85-b828-08946105747b"),
                            ColorHex = "#06B6D4",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dining",
                            ParentCategoryId = new Guid("8c6e5427-76ee-4a4b-9c37-f223ec668754")
                        },
                        new
                        {
                            Id = new Guid("fbdfd64b-5035-41a8-b30a-226efbeabfac"),
                            ColorHex = "#06B6D4",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Transportation",
                            ParentCategoryId = new Guid("8c6e5427-76ee-4a4b-9c37-f223ec668754")
                        },
                        new
                        {
                            Id = new Guid("85b35237-c2d8-4a18-8f99-928d72591808"),
                            ColorHex = "#06B6D4",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Entertainment",
                            ParentCategoryId = new Guid("8c6e5427-76ee-4a4b-9c37-f223ec668754")
                        },
                        new
                        {
                            Id = new Guid("74b7831c-240c-4eaf-8f7e-d8d890ca290d"),
                            ColorHex = "#06B6D4",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("8c6e5427-76ee-4a4b-9c37-f223ec668754")
                        },
                        new
                        {
                            Id = new Guid("da56e738-ee2b-45c0-b40c-2d9112b63adf"),
                            ColorHex = "#EAB308",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = new Guid("f0516a5c-5d9b-45b0-b7d8-ee05e90742d7"),
                            ColorHex = "#EAB308",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Phone",
                            ParentCategoryId = new Guid("da56e738-ee2b-45c0-b40c-2d9112b63adf")
                        },
                        new
                        {
                            Id = new Guid("7cd15891-9c87-4268-a99a-d52368c6a60f"),
                            ColorHex = "#EAB308",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cable",
                            ParentCategoryId = new Guid("da56e738-ee2b-45c0-b40c-2d9112b63adf")
                        },
                        new
                        {
                            Id = new Guid("5ba8fa64-353e-4deb-a9eb-38fcfb6c8c10"),
                            ColorHex = "#EAB308",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Internet",
                            ParentCategoryId = new Guid("da56e738-ee2b-45c0-b40c-2d9112b63adf")
                        },
                        new
                        {
                            Id = new Guid("70817266-9630-4d44-b5ad-77525b10e25d"),
                            ColorHex = "#EAB308",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Electricity",
                            ParentCategoryId = new Guid("da56e738-ee2b-45c0-b40c-2d9112b63adf")
                        },
                        new
                        {
                            Id = new Guid("160d474a-83e0-4eea-a342-19513ec05bf8"),
                            ColorHex = "#EAB308",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gas",
                            ParentCategoryId = new Guid("da56e738-ee2b-45c0-b40c-2d9112b63adf")
                        },
                        new
                        {
                            Id = new Guid("656b821a-4a5e-4ab3-ad98-664cd726a827"),
                            ColorHex = "#EAB308",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Water",
                            ParentCategoryId = new Guid("da56e738-ee2b-45c0-b40c-2d9112b63adf")
                        },
                        new
                        {
                            Id = new Guid("db0fd62e-7b25-49fc-92bd-f7781a1e6f4b"),
                            ColorHex = "#EAB308",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Trash",
                            ParentCategoryId = new Guid("da56e738-ee2b-45c0-b40c-2d9112b63adf")
                        },
                        new
                        {
                            Id = new Guid("bf09a7b1-4c6d-4c14-b468-bb8ebfbcdfed"),
                            ColorHex = "#EAB308",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other",
                            ParentCategoryId = new Guid("da56e738-ee2b-45c0-b40c-2d9112b63adf")
                        },
                        new
                        {
                            Id = new Guid("dceee3e9-3670-4cbc-a617-6ac80cc214d2"),
                            ColorHex = "#9CA3AF",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other"
                        },
                        new
                        {
                            Id = new Guid("7d1867e8-5883-4b1a-a80a-be17a65e00cb"),
                            ColorHex = "#9CA3AF",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Other Expenses",
                            ParentCategoryId = new Guid("dceee3e9-3670-4cbc-a617-6ac80cc214d2")
                        });
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceApp.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4351016e-e3c7-4b4d-9821-073022f26b14",
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultCurrency = "USD",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJqMnnZQkjVdnMLhJYvR83GrrwZW12KF6ikdfHShxEkC4g0xzvPJqXrvmAWk8xgilg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "A70E28B0-8CAE-4DEE-BE39-C79178E89086",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        });
                });

            modelBuilder.Entity("TagTransaction", b =>
                {
                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionsId")
                        .HasColumnType("uuid");

                    b.HasKey("TagsId", "TransactionsId");

                    b.HasIndex("TransactionsId");

                    b.ToTable("transaction_tags", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PersonalFinanceApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PersonalFinanceApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PersonalFinanceApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Category", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TagTransaction", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Domain.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
